### ISSUE TITLE
[Phing\Exception\BuildException] Could not find name of SonarQube Scanner in version string. Executable appears not to be SonarQube Scanner: [sonar-scanner].

### ISSUE THREAD

**Issue by feamsr00** [phingofficial/task-analyzers#2]
Hello!

At some point the name of the scanner changed. It is now **SonarScanner** and no longer _SonarQube Scanner_.

https://github.com/phingofficial/task-analyzers/blob/c5a6c66d1d6243f3110d1272a67714c83c52bf2a/src/Sonar/SonarTask.php#L277

```
>sonar-scanner --version
INFO: Scanner configuration file: C:\exec\ScoopApps\apps\sonar-scanner\current\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarScanner 4.7.0.2747
INFO: Java 19.0.1 Oracle Corporation (64-bit)
INFO: Windows 10 10.0 amd64
```

Hopefully this is the right place to report this?

**Comment by mrook** [comment]
I'll try to roll a new release candidate week after next.
